PLUGIN_NAME=         wallmon
PLUGIN_VERSION=      0.1.0
PLUGIN_COMMENT=      OPNsense package wallmon
PLUGIN_DEPENDS=      dmidecode
PLUGIN_MAINTAINER=   wallmon.ops@nullnet.ai

.include "../../Mk/plugins.mk"
